# coding=utf-8
#Date Revised    Revised by     Revision Note
#--------------- -------------- --------------------------------------------------------------------
# 20221101          xiaowen      初始版本

from Spark_base import SparkBase
import os
os.environ['PYSPARK_PYTHON']= 'E:\study\pyspark_anoconda\envs\pyspark\python.exe'
from pyspark.sql.types import StructType,IntegerType,StringType,StructField

if __name__ == '__main__':
    spark = SparkBase.SparkSql()
    #  公积金表
    file_path = 'E:\z_resource\z_program\XW_PBCPC_HOUSE_HSFD_RECD.xlsx'
    schema = StructType([
        StructField("rpt_id"                  ,StringType(),True),
        StructField("inbk_cust_id"            ,StringType(),True),
        StructField("parti_land"              ,StringType(),True),
        StructField("parti_dt"                ,StringType(),True),
        StructField("parti_sts_cd"            ,StringType(),True),
        StructField("parti_sts_nm"            ,StringType(),True),
        StructField("ini_parti_mon"           ,StringType(),True),
        StructField("pay_to_mon"              ,StringType(),True),
        StructField("corp_parti_pct"          ,StringType(),True),
        StructField("inuv_parti_pct"          ,StringType(),True),
        StructField("mon_parti_amt"           ,StringType(),True),
        StructField("payment_corp"            ,StringType(),True),
        StructField("inf_upd_dt"              ,StringType(),True),
        StructField("new_flag_lst_1y_pay_mon" ,StringType(),True),
        StructField("etl_job"                 ,StringType(),True),
        StructField("dt"                      ,StringType(),True)
    ])
    df = spark.load_data_pandas(file_path,'Sheet1',schema)
    spark.write_to_jdbc(df,'XW_PBCPC_HOUSE_HSFD_RECD')

    #    借贷信息账户信息表
    file_path = 'E:\z_resource\z_program\XW_PBCPC_DRCR_ACCT_TB.xlsx'
    schema = StructType([
        StructField('rpt_id',StringType(),True),
        StructField('inqd_nm',StringType(),True),
        StructField('inqd_cert_type',StringType(),True),
        StructField('inqd_cert_num',StringType(),True),
        StructField('inqd_inbk_cust_id',StringType(),True),
        StructField('inq_instn_cd',StringType(),True),
        StructField('inq_instn_nm',StringType(),True),
        StructField('acct_no',StringType(),True),
        StructField('acct_type_cd',StringType(),True),
        StructField('acct_type_nm',StringType(),True),
        StructField('acct_type_loan_c_card',StringType(),True),
        StructField('acct_type_loan_c_card_nm',StringType(),True),
        StructField('recycal_loan_id',StringType(),True),
        StructField('recycal_loan_id_nm',StringType(),True),
        StructField('bus_mag_inst_tp_cd',StringType(),True),
        StructField('bus_mag_inst_tp_nm',StringType(),True),
        StructField('bus_mag_inst_cd',StringType(),True),
        StructField('bus_mag_inst_nm',StringType(),True),
        StructField('in_oth_bnk',StringType(),True),
        StructField('in_oth_bnk_nm',StringType(),True),
        StructField('inst_type_bnk_yn_one',StringType(),True),
        StructField('inst_type_bnk_yn_one_nm',StringType(),True),
        StructField('inst_type_bnk_yn_two',StringType(),True),
        StructField('inst_type_bnk_yn_two_nm',StringType(),True),
        StructField('acct_id',StringType(),True),
        StructField('credit_agmt_id',StringType(),True),
        StructField('bus_categ_cd',StringType(),True),
        StructField('bus_categ_nm',StringType(),True),
        StructField('biz_categ_pro',StringType(),True),
        StructField('biz_categ_pro_nm',StringType(),True),
        StructField('bus_house_load_id',StringType(),True),
        StructField('mass_sp_ins_id',StringType(),True),
        StructField('open_dt',StringType(),True),
        StructField('opac_ind_lst_30d',StringType(),True),
        StructField('opac_ind_lst_60d',StringType(),True),
        StructField('opac_ind_lst_3m',StringType(),True),
        StructField('opac_ind_lst_6m',StringType(),True),
        StructField('opac_ind_lst_1y',StringType(),True),
        StructField('curr_cd',StringType(),True),
        StructField('curr_nm',StringType(),True),
        StructField('loan_amt',StringType(),True),
        StructField('acct_credit_lmt',StringType(),True),
        StructField('share_credit_lmt',StringType(),True),
        StructField('due_dt',StringType(),True),
        StructField('due_dt_lst_1m',StringType(),True),
        StructField('due_dt_lst_3m',StringType(),True),
        StructField('due_dt_lst_6m',StringType(),True),
        StructField('repay_meth_cd',StringType(),True),
        StructField('repay_meth_nm',StringType(),True),
        StructField('repay_freq_cd',StringType(),True),
        StructField('repay_freq_nm',StringType(),True),
        StructField('one_tm_repay_prin_int_id',StringType(),True),
        StructField('repay_tm',StringType(),True),
        StructField('udtk_meth_cd',StringType(),True),
        StructField('udtk_meth_nm',StringType(),True),
        StructField('udtk_meth_pro',StringType(),True),
        StructField('udtk_meth_pro_nm',StringType(),True),
        StructField('ln_dsph_form_cd',StringType(),True),
        StructField('ln_dsph_form_nm',StringType(),True),
        StructField('comm_indb_ind_cd',StringType(),True),
        StructField('comm_indb_ind_nm',StringType(),True),
        StructField('obli_right_trans_repay_sts_cd',StringType(),True),
        StructField('obli_right_trans_repay_sts_nm',StringType(),True),
        StructField('acct_sts_cd_new_pf',StringType(),True),
        StructField('acct_sts_nm_new_pf',StringType(),True),
        StructField('acct_sts_pro',StringType(),True),
        StructField('acct_sts_pro_nm',StringType(),True),
        StructField('adv_clsd_id',StringType(),True),
        StructField('crdt_excpt_id',StringType(),True),
        StructField('bddb_id',StringType(),True),
        StructField('close_dt_new_pf',StringType(),True),
        StructField('close_id_3m_fro',StringType(),True),
        StructField('close_id_6m_fro',StringType(),True),
        StructField('close_id_1y_fro',StringType(),True),
        StructField('close_id_2y_fro',StringType(),True),
        StructField('trno_dt_new_pf',StringType(),True),
        StructField('bal_new_pf',StringType(),True),
        StructField('lst_repay_dt_lst_new_pf',StringType(),True),
        StructField('lst_repay_amt_lst_new_pf',StringType(),True),
        StructField('five_class_cd_new_pf',StringType(),True),
        StructField('five_class_nm_new_pf',StringType(),True),
        StructField('bad_id',StringType(),True),
        StructField('repay_sts_cd_new_pf',StringType(),True),
        StructField('repay_sts_nm_new_pf',StringType(),True),
        StructField('inf_rpt_dt_new_pf',StringType(),True),
        StructField('month_lst_m_pf',StringType(),True),
        StructField('acct_sts_cd_lst_m_pf',StringType(),True),
        StructField('acct_sts_nm_lst_m_pf',StringType(),True),
        StructField('bal_lst_m_pf',StringType(),True),
        StructField('used_lmt_lst_m_pf',StringType(),True),
        StructField('uiss_mass_sp_insbal_lst_m_pf',StringType(),True),
        StructField('five_class_cd_lst_m_pf',StringType(),True),
        StructField('five_class_nm_lst_m_pf',StringType(),True),
        StructField('residu_rep_tm_lst_m_pf',StringType(),True),
        StructField('settle_payabl_dt_lst_m_pf',StringType(),True),
        StructField('new_balance_lst_m_pf',StringType(),True),
        StructField('actual_repay_lst_m_pf',StringType(),True),
        StructField('lst_refund_dt_lst_m_pf',StringType(),True),
        StructField('cur_ovdu_tm_lst_m_pf',StringType(),True),
        StructField('cur_ovdu_tot_amt_lst_m_pf',StringType(),True),
        StructField('ovdu_ind_cur',StringType(),True),
        StructField('ovdu_90_upr_ind_cur',StringType(),True),
        StructField('ovdu_31_60d_owepr_lst_m_pf',StringType(),True),
        StructField('ovdu_61_90d_owepr_lst_m_pf',StringType(),True),
        StructField('ovdu_91_180d_owepr_lst_m_pf',StringType(),True),
        StructField('ovdu_180d_upr_owepr_lst_m_pf',StringType(),True),
        StructField('od_180d_upr_snpbal_lst_m_pf',StringType(),True),
        StructField('lst_6m_avg_use_lmt_lst_m_pf',StringType(),True),
        StructField('lst_6m_avg_od_bal_lst_m_pf',StringType(),True),
        StructField('max_use_lmt_lst_m_pf',StringType(),True),
        StructField('max_od_bal_lst_m_pf',StringType(),True),
        StructField('inf_rpt_dt_lst_m_pf',StringType(),True),
        StructField('mass_spec_instl_qty',StringType(),True),
        StructField('highest_ovdu_term',StringType(),True),
        StructField('max_ovdu_tm_lst_6m',StringType(),True),
        StructField('max_ovdu_tm_lst_1y',StringType(),True),
        StructField('max_ovdu_tm_lst_2y',StringType(),True),
        StructField('accum_ovdu_tm',StringType(),True),
        StructField('tot_ovdu_tm_lst_6m',StringType(),True),
        StructField('tot_ovdu_tm_lst_1y',StringType(),True),
        StructField('tot_ovdu_tm_lst_2y',StringType(),True),
        StructField('ovdu_id_lst_18m',StringType(),True),
        StructField('ovdu_id_lst_2y',StringType(),True),
        StructField('fst_four_trm_ovdu_60d_upr_id',StringType(),True),
        StructField('ovdu_30d_upr_id_lst_3m',StringType(),True),
        StructField('ovdu_30d_upr_id_lst_6m',StringType(),True),
        StructField('ovdu_30d_upr_id_lst_1y',StringType(),True),
        StructField('ovdu_30d_upr_id_lst_2y',StringType(),True),
        StructField('ovdu_60d_upr_id_lst_3m',StringType(),True),
        StructField('ovdu_60d_upr_id_lst_6m',StringType(),True),
        StructField('ovdu_60d_upr_id_lst_1y',StringType(),True),
        StructField('ovdu_60d_upr_id_lst_2y',StringType(),True),
        StructField('ovdu_90d_upr_id_his',StringType(),True),
        StructField('ovdu_samt_lst_3m_30a',StringType(),True),
        StructField('ovdu_samt_lst_6m_30a',StringType(),True),
        StructField('ovdu_samt_lst_1y_30a',StringType(),True),
        StructField('ovdu_samt_lst_2y_30a',StringType(),True),
        StructField('ovdu_samt_lst_3m_60a',StringType(),True),
        StructField('ovdu_samt_lst_6m_60a',StringType(),True),
        StructField('ovdu_samt_lst_1y_60a',StringType(),True),
        StructField('ovdu_samt_lst_2y_60a',StringType(),True),
        StructField('tot_ovdu_m1_tm_lst_1y',StringType(),True),
        StructField('tot_ovdu_m2_tm_lst_1y',StringType(),True),
        StructField('tot_ovdu_m3_upr_tm_lst_1y',StringType(),True),
        StructField('nor_rfn_tm_lst_6m',StringType(),True),
        StructField('nor_rfn_tm_lst_1y',StringType(),True),
        StructField('nor_rfn_tm_lst_2y',StringType(),True),
        StructField('lmt_used_wacct_spe_card',StringType(),True),
        StructField('ltst_ovdu_tm_long',StringType(),True),
        StructField('loan_excs_pcy_hs_spe',StringType(),True),
        StructField('loan_excs_pcy_hs_spe_nm',StringType(),True),
        StructField('prms_val_esti_coeff_mtgg_spe',StringType(),True),
        StructField('prms_val_esti_mtgg_spe',StringType(),True),
        StructField('data_rsue',StringType(),True),
        StructField('etl_job',StringType(),True),
        StructField('dt',StringType(),True)
    ])
    df = spark.load_data_pandas(file_path,'Sheet1',schema)
    spark.write_to_jdbc(df,'XW_PBCPC_DRCR_ACCT_TB')

    #  人行征信2.0主表
    file_path = 'E:\z_resource\z_program\XW_PBCPC_MAIN_TB.xlsx'
    schema = StructType([
        StructField('rpt_id',StringType(),True),
        StructField('rpt_dt',StringType(),True),
        StructField('inqd_nm',StringType(),True),
        StructField('inqd_cert_type',StringType(),True),
        StructField('inqd_cert_num',StringType(),True),
        StructField('inqd_inbk_cust_id',StringType(),True),
        StructField('inq_instn_cd',StringType(),True),
        StructField('inq_instn_nm',StringType(),True),
        StructField('inq_rsn_cd',StringType(),True),
        StructField('inq_rsn_nm',StringType(),True),
        StructField('fraud_wn_flg_cd',StringType(),True),
        StructField('fraud_wn_flg_nm',StringType(),True),
        StructField('fraud_wn_flg_tel',StringType(),True),
        StructField('fraud_wn_flg_eff_dt',StringType(),True),
        StructField('fraud_wn_flg_cut_dt',StringType(),True),
        StructField('dissent_mrk_qty',StringType(),True),
        StructField('sex_cd',StringType(),True),
        StructField('sex_nm',StringType(),True),
        StructField('birthday',StringType(),True),
        StructField('educ_cd_pboc',StringType(),True),
        StructField('educ_nm_pboc',StringType(),True),
        StructField('degree_cd_pboc',StringType(),True),
        StructField('degree_nm_pboc',StringType(),True),
        StructField('eply_sts_cd_pboc',StringType(),True),
        StructField('eply_sts_nm_pboc',StringType(),True),
        StructField('email_pboc',StringType(),True),
        StructField('comm_addr_pboc',StringType(),True),
        StructField('naty_cd',StringType(),True),
        StructField('naty',StringType(),True),
        StructField('rsd_addr_pboc',StringType(),True),
        StructField('mo_phone_num',StringType(),True),
        StructField('last_mo_phone',StringType(),True),
        StructField('mrg_cond_cd_pboc',StringType(),True),
        StructField('mrg_cond_nm_pboc',StringType(),True),
        StructField('spouse_nm',StringType(),True),
        StructField('spouse_cert_type_cd',StringType(),True),
        StructField('spouse_cert_type_nm',StringType(),True),
        StructField('spouse_cert_nm',StringType(),True),
        StructField('spouse_corp_pboc',StringType(),True),
        StructField('spouse_tel_pboc',StringType(),True),
        StructField('digital_unscramble',StringType(),True),
        StructField('elative_locat',StringType(),True),
        StructField('scor_desc_qty',StringType(),True),
        StructField('scor_desc_cd',StringType(),True),
        StructField('scor_desc_nm',StringType(),True),
        StructField('mas_instn_num_non_rev_loan',StringType(),True),
        StructField('acct_num_non_rev_loan',StringType(),True),
        StructField('credit_tot_amt_non_rev_loan',StringType(),True),
        StructField('bal_non_rev_loan',StringType(),True),
        StructField('last_6m_avr_ap_non_rev_loan',StringType(),True),
        StructField('mas_instn_num_udrevlmt_acct',StringType(),True),
        StructField('acct_num_udrevlmt_acct',StringType(),True),
        StructField('credit_tot_udrevlmt_acct',StringType(),True),
        StructField('bal_udrevlmt_acct',StringType(),True),
        StructField('last_6m_avr_ap_udrevlmt_acct',StringType(),True),
        StructField('mas_instn_num_rev_loan',StringType(),True),
        StructField('acct_num_rev_loan',StringType(),True),
        StructField('credit_tot_rev_loan',StringType(),True),
        StructField('bal_rev_loan',StringType(),True),
        StructField('last_6m_avr_ap_rev_loan',StringType(),True),
        StructField('iss_crd_instnc_num_c_card',StringType(),True),
        StructField('acct_num_c_card',StringType(),True),
        StructField('credit_tot_c_card',StringType(),True),
        StructField('per_bnk_credit_max_c_card',StringType(),True),
        StructField('per_bnk_credit_min_c_card',StringType(),True),
        StructField('used_crlmt_c_card',StringType(),True),
        StructField('last_6m_avr_use_crmt_c_card',StringType(),True),
        StructField('iss_crd_instnc_num_q_c_card',StringType(),True),
        StructField('acct_num_q_c_card',StringType(),True),
        StructField('credit_tot_q_c_card',StringType(),True),
        StructField('per_bnk_credit_max_q_c_card',StringType(),True),
        StructField('per_bnk_credit_min_q_c_card',StringType(),True),
        StructField('ovdrt_bal_q_c_card',StringType(),True),
        StructField('last_6m_avovbal_q_c_card',StringType(),True),
        StructField('payg_aft_biz_num',StringType(),True),
        StructField('owe_fee_acct_nm_aft_biz_tel',StringType(),True),
        StructField('owe_fee_amt_payg_aft_biz_tel',StringType(),True),
        StructField('owe_fee_acct_nm_aft_biz_pub',StringType(),True),
        StructField('owe_fee_amt_payg_aft_biz_pub',StringType(),True),
        StructField('ltm_inq_dt',StringType(),True),
        StructField('ltm_inq_instn_type_cd',StringType(),True),
        StructField('ltm_inq_instn_type_nm',StringType(),True),
        StructField('ltm_inq_instn_cd',StringType(),True),
        StructField('ltm_inq_instn_nm',StringType(),True),
        StructField('ltm_inq_rsn_cd',StringType(),True),
        StructField('ltm_inq_rsn_nm',StringType(),True),
        StructField('last_1m_inq_ins_num_loan_adt',StringType(),True),
        StructField('last_1m_inq_ins_num_crcd_adt',StringType(),True),
        StructField('last_1m_inq_num_loan_adt',StringType(),True),
        StructField('last_1m_inq_num_crcd_adt',StringType(),True),
        StructField('last_1m_inq_num_bf',StringType(),True),
        StructField('last_2y_inq_num_aft_ln_mg',StringType(),True),
        StructField('last_2y_inq_num_udtk_qa_insp',StringType(),True),
        StructField('last_2y_inq_num_apt_mch_insp',StringType(),True),
        StructField('public_info_type_num',StringType(),True),
        StructField('acct_num_totl_be_recvrd',StringType(),True),
        StructField('bal_totl_be_recvrd',StringType(),True),
        StructField('acct_num_baddue',StringType(),True),
        StructField('bal_baddue',StringType(),True),
        StructField('civl_jugmt_ind',StringType(),True),
        StructField('admin_pnish_ind',StringType(),True),
        StructField('owe_tax_ind',StringType(),True),
        StructField('lowincm_ind',StringType(),True),
        StructField('forced_excution_ind',StringType(),True),
        StructField('data_rsue',StringType(),True),
        StructField('etl_job',StringType(),True),
        StructField('dt',StringType(),True)
    ])
    df = spark.load_data_pandas(file_path,'Sheet1',schema)
    spark.write_to_jdbc(df,'XW_PBCPC_MAIN_TB')